import type { ColDef } from 'ag-grid-community'

export type AthleteRow = {
  id: number
  athlete: string
  age: number
  country: string
  year: number
  date: string
  sport: string
  gold: number
  silver: number
  bronze: number
  total: number
  active: boolean
  qualifyingTime: number
  ranking: number
  region: string
}

export const simpleColumnDefs: ColDef<AthleteRow>[] = [
  { field: 'athlete', minWidth: 180 },
  { field: 'age', maxWidth: 110 },
  { field: 'country', minWidth: 150 },
  { field: 'year', maxWidth: 110 },
  { field: 'date', minWidth: 140 },
  { field: 'sport', minWidth: 160 },
  { field: 'gold', maxWidth: 110 },
  { field: 'silver', maxWidth: 110 },
  { field: 'bronze', maxWidth: 110 },
  { field: 'total', maxWidth: 110 },
]

export const complexColumnDefs: ColDef<AthleteRow>[] = [
  {
    field: 'athlete',
    minWidth: 220,
    pinned: 'left',
    checkboxSelection: true,
    headerCheckboxSelection: true,
  },
  { field: 'country', minWidth: 170, hide: true },
  { field: 'region', minWidth: 160 },
  { field: 'sport', minWidth: 170 },
  { field: 'year', maxWidth: 110 },
  { field: 'gold', maxWidth: 110 },
  { field: 'silver', maxWidth: 110 },
  { field: 'bronze', maxWidth: 110 },
  { field: 'total', maxWidth: 110 },
  {
    field: 'qualifyingTime',
    headerName: 'Qualifier',
    minWidth: 140,
    valueFormatter: ({ value }) => `${value.toFixed(2)}s`,
  },
  {
    field: 'ranking',
    maxWidth: 120,
    filter: 'agNumberColumnFilter',
  },
  {
    field: 'active',
    maxWidth: 120,
    cellRenderer: ({ value }: { value?: boolean }) => (value ? 'Active' : 'Retired'),
  },
]

export const athleteRows: AthleteRow[] = [
  {
    id: 1,
    athlete: 'Michael Phelps',
    age: 23,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 8,
    silver: 0,
    bronze: 0,
    total: 8,
    active: false,
    qualifyingTime: 50.91,
    ranking: 1,
    region: 'North America',
  },
  {
    id: 2,
    athlete: 'Usain Bolt',
    age: 22,
    country: 'Jamaica',
    year: 2008,
    date: '24/08/2008',
    sport: 'Athletics',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 3,
    active: false,
    qualifyingTime: 9.69,
    ranking: 1,
    region: 'Caribbean',
  },
  {
    id: 3,
    athlete: 'Simone Biles',
    age: 19,
    country: 'United States',
    year: 2016,
    date: '21/08/2016',
    sport: 'Gymnastics',
    gold: 4,
    silver: 0,
    bronze: 1,
    total: 5,
    active: true,
    qualifyingTime: 57.4,
    ranking: 1,
    region: 'North America',
  },
  {
    id: 4,
    athlete: 'Katie Ledecky',
    age: 19,
    country: 'United States',
    year: 2016,
    date: '21/08/2016',
    sport: 'Swimming',
    gold: 4,
    silver: 1,
    bronze: 0,
    total: 5,
    active: true,
    qualifyingTime: 245.12,
    ranking: 1,
    region: 'North America',
  },
  {
    id: 5,
    athlete: 'Allyson Felix',
    age: 30,
    country: 'United States',
    year: 2016,
    date: '21/08/2016',
    sport: 'Athletics',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    active: false,
    qualifyingTime: 49.26,
    ranking: 2,
    region: 'North America',
  },
  {
    id: 6,
    athlete: 'Mo Farah',
    age: 33,
    country: 'Great Britain',
    year: 2016,
    date: '21/08/2016',
    sport: 'Athletics',
    gold: 2,
    silver: 0,
    bronze: 0,
    total: 2,
    active: false,
    qualifyingTime: 812.33,
    ranking: 1,
    region: 'Europe',
  },
  {
    id: 7,
    athlete: 'Elaine Thompson-Herah',
    age: 29,
    country: 'Jamaica',
    year: 2021,
    date: '08/08/2021',
    sport: 'Athletics',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 3,
    active: true,
    qualifyingTime: 10.61,
    ranking: 1,
    region: 'Caribbean',
  },
  {
    id: 8,
    athlete: 'Caeleb Dressel',
    age: 24,
    country: 'United States',
    year: 2021,
    date: '08/08/2021',
    sport: 'Swimming',
    gold: 5,
    silver: 0,
    bronze: 0,
    total: 5,
    active: true,
    qualifyingTime: 49.45,
    ranking: 1,
    region: 'North America',
  },
  {
    id: 9,
    athlete: 'Sunisa Lee',
    age: 18,
    country: 'United States',
    year: 2021,
    date: '08/08/2021',
    sport: 'Gymnastics',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    active: true,
    qualifyingTime: 54.25,
    ranking: 3,
    region: 'North America',
  },
  {
    id: 10,
    athlete: 'Faith Kipyegon',
    age: 27,
    country: 'Kenya',
    year: 2021,
    date: '08/08/2021',
    sport: 'Athletics',
    gold: 1,
    silver: 0,
    bronze: 0,
    total: 1,
    active: true,
    qualifyingTime: 233.11,
    ranking: 1,
    region: 'Africa',
  },
]